/*****************************************************************************
 * Project: RooFit *
 * *
 * This code was autogenerated by RooClassFactory *
 *****************************************************************************/

#ifndef POLYPOWER
#define POLYPOWER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class PolyPower : public RooAbsPdf {
 public:
  PolyPower() {} ;
  PolyPower(const char *name, const char *title,
	   RooAbsReal& _x,
	   RooAbsReal& _p0,
	   RooAbsReal& _p1);
  PolyPower(const PolyPower& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PolyPower(*this,newname); }
  inline virtual ~PolyPower() { }

 protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  
  Double_t evaluate() const ;

 private:

  ClassDef(PolyPower,1) // Your description goes here...
    };
 
#endif
