/*****************************************************************************
 * Project: RooFit *
 * *
 * This code was autogenerated by RooClassFactory *
 *****************************************************************************/

// pow( x^2 + ax + b, c )
// Phil Hebda
// 9/12/2013

#include "Riostream.h"

#include "PolyPower.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(PolyPower)

  PolyPower::PolyPower(const char *name, const char *title,
		     RooAbsReal& _x,
		     RooAbsReal& _p0,
		     RooAbsReal& _p1) :
    RooAbsPdf(name,title),
    x("x","x",this,_x),
    p0("p0","p0",this,_p0),
    p1("p1","p1",this,_p1)
{
}


PolyPower::PolyPower(const PolyPower& other, const char* name) :
  RooAbsPdf(other,name),
  x("x",this,other.x),
  p0("p0",this,other.p0),
  p1("p1",this,other.p1)
{
}

Double_t PolyPower::evaluate() const
{
  Double_t result=pow( pow(x,2) + p0, p1 );
   
  return result;
}



